add release build for code magic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -42,3 +42,111 @@ workflows:
       - name: Analyzing
         working_directory: /Users/builder/clone/app_files
         script: flutter analyze
+
+
+  create-version:
+    name: Create version
+    instance_type: mac_mini_m1
+    max_build_duration: 10
+    environment:
+      groups:
+        - frontend
+      flutter: 3.10.5
+      xcode: latest
+    cache:
+      cache_paths:
+        - ~/.pub-cache
+    scripts:
+      - name: Cloning pubdev_registry repo
+        working_directory: /Users/builder
+        script: |
+          rm -rf clone/*
+          git clone git@github.com:futurehomeno/yggdrasil.git $CM_BUILD_DIR/app_files
+          cd $CM_BUILD_DIR/app_files
+          git checkout $CM_BRANCH
+
+      - name: Downloading flutter cli
+        script: |
+          git clone git@github.com:futurehomeno/flutter-cli.git $CM_BUILD_DIR/cli
+          cd $CM_BUILD_DIR/cli
+          flutter pub get
+
+      - name: Creating version
+        working_directory: /Users/builder/clone/app_files
+        script: dart $CM_BUILD_DIR/cli/futurehome.dart ci cav -ai -uc || exit 1
+
+
+  android-release:
+    name: Android release
+    instance_type: mac_mini_m1
+    max_build_duration: 30
+
+    environment:
+      groups:
+        - frontend
+      android_signing:
+        - yggdrasil_keystore
+      flutter: 3.10.5
+
+    triggering:
+      events:
+        - tag
+      tag_patterns:
+        - pattern: '*'
+          include: true
+      cancel_previous_builds: true
+
+    scripts:
+      - name: Set up local.properties
+        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
+
+      - name: Get Flutter packages
+        script: flutter packages pub get
+
+      - name: Build AAB with Flutter
+        script: flutter build appbundle --release
+
+      - name: Send artifacts to github
+        script: |
+          #!/bin/sh
+
+          # Change these variables accordingly
+          REPO = "futurehomeno/yggdrasil"
+          ARTIFACT_PATH = "path/to/your/artifact.ext"
+          TAG = $CM_TAG
+          
+          # Create a new release
+          RELEASE_RESPONSE=$(
+            curl --data "{
+              \"tag_name\": \"$TAG\", 
+              \"name\": \"TAG\", 
+              \"body\": \"Release description\", 
+              \"draft\": false, 
+              \"prerelease\": false
+            }" \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Content-Type: application/json" \
+            -X POST "https://api.github.com/repos/$REPO/releases"
+          )
+          
+          echo $RELEASE_RESPONSE
+          
+          # Extract the upload URL from the release response
+          UPLOAD_URL=$(echo $RELEASE_RESPONSE | jq -r .upload_url | sed -e "s/{?name,label}//")
+            
+          if [ -z "$UPLOAD_URL" ]; then
+            echo "Failed to get upload URL"
+            exit 1
+          fi
+            
+          # Upload the artifact
+          curl -X POST \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Content-Type: $(file -b --mime-type $ARTIFACT_PATH)" \
+            --data-binary "@$ARTIFACT_PATH" \
+            "$UPLOAD_URL?name=$(basename $ARTIFACT_PATH)"
+
+    artifacts:
+      - build/ios/ipa/*.ipa
+      - /tmp/xcodebuild_logs/*.log
+      - flutter_drive.log
